#!/usr/bin/python
##::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::
##
##        This file is part of E-CELL Simulation Environment package
##
##                Copyright (C) 2000 - 2001 E-CELL Project
##
##::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::
##
##
## dmtool is free software; you can redistribute it and/or
## modify it under the terms of the GNU General Public
## License as published by the Free Software Foundation; either
## version 2 of the License, or (at your option) any later version.
## 
## dmtool is distributed in the hope that it will be useful,
## but WITHOUT ANY WARRANTY; without even the implied warranty of
## MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
## See the GNU General Public License for more details.
## 
## You should have received a copy of the GNU General Public
## License along with dmtool -- see the file COPYING.
## If not, write to the Free Software Foundation, Inc.,
## 59 Temple Place - Suite 330, Boston, MA 02111-1307, USA.
## 
##END_HEADER
##
## written by Yusuke Saito <zhaiteng@e-cell.org> and
##            Kouichi Takahashi <shafi@e-cell.org> at
## E-CELL Project, Institute for Advanced Biosciences, Keio University
##


## standard module ##

import sys
import re
import string
import os
import glob


class DmFile:
      
      commentRegex = re.compile( r'^\#' )
      nlRegex      = re.compile( r'^\n' )
      patternRegex = re.compile( r'([\@\%])(\w+):\s*(.*)' )

      def __init__( self, infilename ):
            self.dic = {}
            self.keynum = {}
            self.property = {}
            self.out = ''
            self.prekey = ''
            self.read( infilename )

      def read( self, infile ):
            self.file = infile
            try:
                  fp = open( self.file, 'r' )
            except:	
                  print self.file, ": file not found."
                  sys.exit( 1 )
            while 1:
                  line = fp.readline()

                  # End of file
                  if not line:
                        break

                  # skip comment or empty line
                  if DmFile.commentRegex.match( line )\
                     or DmFile.nlRegex.match( line ):
                        continue
                  match = DmFile.patternRegex.match( line )               
                  if not match:
                        self.dic[self.prekey] = self.dic[self.prekey] + line
                        continue

                  type  = match.group( 1 )                  
                  key   = match.group( 2 )                                    
                  value = match.group( 3 )
                  
                  if key == self.prekey:                  
                        self.keynum[key] = self.keynum[key] + 1
                        #print key
                  else:
                        self.keynum[key] = 0
                        #print key
                        self.property[key] = {}
                  
                  # get it!
                  self.dic[key] = value

                  # array type                   
                  if type == "%":
                        list = string.splitfields( value, "," )
                        self.property[key][self.keynum[key]] = list
                  self.prekey = key

class DmTemplate:

      regex1 = re.compile( r'\#\(\@(\w+)\)' )
      regex2 = re.compile( r'\#\(\%(.+)\)' )
      regex3 = re.compile( r'\#\(\&(\w+:\w+)\)' )

      def __init__( self, templatedir ):
            self.templatedir = templatedir
      
      def setDmFile( self, dmfile ):
            self.dmfile = dmfile

      def write( self, dmfile, mastertemplate, outfile ):
            try:
                  fp = open( outfile, 'w' )
            except:
                  print "Couldn't write " + outfile + "."
                  sys.exit( 1 )
            buffer = self.generate( mastertemplate )

            # flush the buffer
            fp.write( buffer )
            fp.close()

      def generate( self, keyname , no = 0):
            buffer = ''
            template_file = self.templatedir + '/' + keyname
            try:
                  tp = open( template_file, 'r' )
            except:
                  print "template " + template_file + ": not found."
                  sys.exit( 1 )
            while 1:
                  line = tp.readline()
                  
                  if not line:
                        break

                  if DmTemplate.regex1.search( line ):
                        line = self.sub( line , no)                                                
                        buffer = buffer + line
                        continue

                  match = DmTemplate.regex2.search( line )
                  if match:
                        name = match.group( 1 )
                        line = ''
                        key = string.split( name , ':' )
                        for i in range (len(self.dmfile.property[key[1]])): 
                              line =  line + self.generate( key[0] , i)
                        buffer = buffer + line
                        continue
                        
                  match = DmTemplate.regex3.search( line )
                  if match:
                                                
                        line = self.sub( line ,no )
                        buffer = buffer + line                        
                        continue
                  
                  buffer = buffer + line
            return buffer

      def sub( self, line ,no = 0):
            buffer = ''
            while 1:

                  flg = 0

                  match = DmTemplate.regex1.search( line )
                  if match:
                        key = match.group( 1 )
                        if not self.dmfile.dic.has_key( key ):
                              print "Keyword " + key + " not found."
                              sys.exit( 1 )
                        line = string.replace( line , '#(@'+key+')', self.dmfile.dic[key])
                        flg = 1
            
                  match = DmTemplate.regex2.search( line )
                  if match:
                        line = ''
                        flg = 1

                  match = DmTemplate.regex3.search( line )
                  if match:
                        key = match.group( 1 )
			subkey = string.split(key , ':')
			if not self.dmfile.dic.has_key( subkey[0] ):
                              print "Keyword " + key + " not found."
                              sys.exit( 1 )			
			
			if subkey[1] == 'c':
                              
			      subname = string.strip(self.dmfile.property[subkey[0]][no][1] )
		              subname = self.checkParameterType( subname )
			else:
			      subname = string.strip(self.dmfile.property[subkey[0]][no][string.atoi(subkey[1])] )
                        
			line = string.replace( line , '#(&'+key+')', subname)
                        flg = 1

                  if flg == 0:
                        buffer = line
                        break

            return buffer
	             

      def checkParameterType( self, type):      
	
	    if type == 'Int':
		  type = '0'
		  
	    elif type == 'Float':
     	          type = '0.0'
	    
	    elif type == 'String':	
	          type = ' /'/' '
	    else:
		print type+' is not defined.'

	    return type

if __name__ == "__main__":
      
      import getopt
      
      def printHelp():
            print sys.argv[0], \
                  """[-h] [-d outdir] [-o outprefix] [-t templatedir]"""\
                  """infile"""

      outprefix = ''
      outdir = '.'
      templatedir = './templates/reactor'

      masterprefix = 'reactor'

      try:
            opts, pargs = getopt.getopt( sys.argv[1:],\
                                         'ho:t:d:' )
      except getopt.GetoptError, e:
            print e
            sys.exit( 1 )

      for opt, arg in opts:
            if opt == '-h':
                  printHelp()
                  sys.exit( 0 )
            elif opt == '-d':
                  outdir = arg
            elif opt == '-o':
                  outprefix = arg                  
            elif opt == '-t':
                  templatedir = arg
            else:
                  print "invalid option:", opt
                  sys.exit( 1 )
      
      infilename = pargs[0]
      
      if infilename == '':
            printHelp()
            sys.exit( 1 )
      
      dmfile = DmFile( infilename )
      
      dmtemplate = DmTemplate( templatedir )
      dmtemplate.setDmFile( dmfile )

      # mastertemplates = templatedir/MASTER.*

      mastertemplates = templatedir + "/" + masterprefix + ".*"

      os.path.expanduser( mastertemplates )
      os.path.expandvars( mastertemplates )
      mastertemplates = glob.glob( mastertemplates )
      
      if len( mastertemplates ) == 0:
            print "no template found in [" + templatedir + "]."
            sys.exit( 1 )

      # generate file for each master template

      filename = string.split( infilename , '.')     

      if outprefix == '':
            outprefix = filename[0]

      for template in mastertemplates:
            
            templatesparts = string.split( template , '/')             
            dmname = string.split( templatesparts[-1], '.')
            outfile = outdir + '/' + outprefix + '.' + dmname[-2]   
            print outfile
            dmtemplate.write( dmfile, os.path.basename( template ), outfile )




























































