



/* #undef HAVE_MOTIF */
/* #undef HAVE_XP */
#undef HAVE_XPM
#undef PACKAGE
#undef VERSION
#undef USE_LONGJMP

#undef DM_SHARE_DIR
#undef ER_MACRO_DIR
#undef ECELL_INCLUDE_DIR
#undef DM_SO_DIR

#undef HAVE_EXCEPTIONS
#undef HAVE_PRETTY_FUNCTION
#undef HAVE_STD_EXCEPTIONS
#undef HAVE_TYPEINFO
