
PACKAGE=ecell
ECELL_MAJOR_VERSION=3
ECELL_MINOR_VERSION=1
ECELL_MICRO_VERSION=105
VERSION=$ECELL_MAJOR_VERSION.$ECELL_MINOR_VERSION.$ECELL_MICRO_VERSION
PACKAGE_DIRNAME=ecell${ECELL_MAJOR_VERSION}-${ECELL_MINOR_VERSION}
