ECELL_MAJOR_VERSION=3
ECELL_MINOR_VERSION=2
ECELL_MICRO_VERSION=0
ECELL_PACKAGE_REVISION=p1
ECELL_VERSION_NUMBER=${ECELL_MAJOR_VERSION}.${ECELL_MINOR_VERSION}.${ECELL_MICRO_VERSION}${ECELL_PACKAGE_REVISION}
