
from ConfirmWindow import *

# Layout constants

# object types:
LE_OBJECT_SYSTEM = 0
LE_OBJECT_PROCESS = 1
LE_OBJECT_VARIABLE = 2
LE_OBJECT_TEXTBOX = 3
LE_OBJECT_CUSTOM = 4
LE_OBJECT_CONNECTION = 5



# ModelStore constants

MS_STEPPER_CLASS = 0
MS_STEPPER_PROPERTYLIST = 1
MS_STEPPER_INFO = 2
MS_STEPPER_SYSTEMLIST = 'SystemList'
MS_STEPPER_PROCESSLIST = 'ProcessList'
MS_VARIABLE_PROCESSLIST = 'ProcessList'
MS_PROCESS_VARREFLIST = 'VariableReferenceList'

MS_PROPERTY_VALUE = 0
MS_PROPERTY_FLAGS = 1
MS_PROPERTY_TYPE = 2

MS_SETTABLE_FLAG = 0
MS_GETTABLE_FLAG = 1
MS_DELETEABLE_FLAG = 4

MS_VARREF_NAME = 0
MS_VARREF_FULLID = 1
MS_VARREF_COEF = 2


MS_SYSTEM_STEPPERID = 'StepperID'
MS_PROCESS_STEPPERID = 'StepperID'


MS_ENTITY_CLASS = 0
MS_ENTITY_PROPERTYLIST = 1
MS_ENTITY_PARENT = 2
MS_ENTITY_CHILD_SYSTEMLIST = 3
MS_ENTITY_CHILD_PROCESSLIST = 4
MS_ENTITY_CHILD_VARIABLELIST = 5
MS_ENTITY_INFO = 6

MS_SYSTEM_ROOT = 'System::/'



# DM constants
ECELL_PROPERTY_SETTABLE_FLAG = 0

DM_DESCRIPTION = "DESCRIPTION"
DM_ACCEPTNEWPROPERTY = "ACCEPTNEWPROPERTY"
DM_PROPERTYLIST ="PROPERTYLIST"

DM_PROPERTY_DEFAULTVALUE = "DEFAULTVALUE"
DM_PROPERTY_SETTABLE_FLAG = "SETTABLEFLAG"
DM_PROPERTY_GETTABLE_FLAG = "GETTABLEFLAG"
DM_PROPERTY_DELETEABLE_FLAG = "DELETEABLEFLAG"
DM_PROPERTY_TYPE = "TYPE"

DM_PROPERTY_STRING = "STRING"
DM_PROPERTY_MULTILINE = "MULTILINE"
DM_PROPERTY_NESTEDLIST = "NESTED_LIST"
DM_PROPERTY_INTEGER = "INTEGER"
DM_PROPERTY_FLOAT = "FLOAT"

DM_SYSTEM_CLASS = 'CompartmentSystem'
DM_SYSTEM_CLASS_OLD = 'System'

DM_VARIABLE_CLASS = 'Variable'



# message types
ME_PLAINMESSAGE = 0
ME_OKCANCEL = 1
ME_YESNO = 2
ME_WARNING = 3
ME_ERROR = 4

ME_RESULT_OK = OK_PRESSED
ME_RESULT_CANCEL = CANCEL_PRESSED

# propertyattributes
ME_GETTABLE_FLAG = MS_GETTABLE_FLAG
ME_SETTABLE_FLAG = MS_SETTABLE_FLAG
ME_DELETEABLE_FLAG = MS_DELETEABLE_FLAG

ME_ROOTID = 'System::/'

# varref indexes
ME_VARREF_NAME = 0
ME_VARREF_FULLID = 1
ME_VARREF_COEF = 2

# entity types
ME_SYSTEM_TYPE = "System"
ME_VARIABLE_TYPE = "Variable"
ME_PROCESS_TYPE = "Process"
ME_STEPPER_TYPE = "Stepper"
ME_PROPERTY_TYPE = "Property"

# special properties
ME_STEPPER_SYSTEMLIST = MS_STEPPER_SYSTEMLIST
ME_STEPPER_PROCESSLIST = MS_STEPPER_PROCESSLIST
ME_VARIABLE_PROCESSLIST = MS_VARIABLE_PROCESSLIST
ME_PROCESS_VARREFLIST = MS_PROCESS_VARREFLIST
ME_STEPPERID = MS_SYSTEM_STEPPERID

#special editor type
ME_ENTITY_EDITOR = 'ME_ENTITY_EDITOR'
ME_CONNNECTION_OBJ_EDITOR = 'ME_CONNNECTION_OBJ_EDITOR'

# undo
MAX_REDOABLE_COMMAND = 20

# ADCP flags
ME_ADD_FLAG = 0
ME_DELETE_FLAG = 1
ME_COPY_FLAG = 2
ME_PASTE_FLAG = 3
ME_EDIT_FLAG = 4
ME_BROWSE_FLAG = 5

ME_FLAGS_NO = 6

# varrefs
ME_VARREF_FULLID = 1

### PATHWAYEDITOR CONSTANTS
# direction
DIRECTION_UP = 1
DIRECTION_DOWN = 2
DIRECTION_LEFT = 4
DIRECTION_RIGHT = 8

# CURSOR types
CU_POINTER = 0
CU_MOVE = 1
CU_ADD = 2
CU_RESIZE_TOP_LEFT = 3
CU_RESIZE_TOP = 4
CU_RESIZE_TOP_RIGHT = 5
CU_RESIZE_RIGHT = 6
CU_RESIZE_BOTTOM_RIGHT = 7
CU_RESIZE_BOTTOM = 8
CU_RESIZE_BOTTOM_LEFT = 9
CU_RESIZE_LEFT = 10


#4- up, 5, down, 

# object types
OB_TYPE_PROCESS = "Process"
OB_TYPE_VARIABLE = "Variable"
OB_TYPE_SYSTEM = "System"
OB_TYPE_TEXT = "Text"
OB_TYPE_CONNECTION = "Connection"

OB_MIN_WIDTH = 80
OB_MIN_HEIGTH = 40

# object properties
OB_POS_X = 'x'
OB_POS_Y = 'y'
OB_FULLID = 'FullID'
OB_STEPPERID = 'StepperID'
OB_TYPE = 'Type'
OB_DIMENSION_X = 'DimensionX'
OB_DIMENSION_Y = 'DimensionY'
OB_HASFULLID = 'HasFullID'

OB_OUTLINE_COLOR = "OutlineColor"
OB_FILL_COLOR = "FillColor"
OB_TEXT_COLOR = "TextColor"
OB_OUTLINE_WIDTH = "Outline"

OB_SHAPE_TYPE = "ShapeType"
OB_SHAPEDESCRIPTORLIST = "ShapeDescriptorList"



# connection constants
# directions
PROCESS_TO_VARIABLE = 0
VARIABLE_TO_PROCESS = 1

# connection properties
CO_PROCESS_ATTACHED = "ProcessAttached"  # this is an OBJECT!
CO_VARIABLE_ATTACHED = "VariableAttached" # this is an OBJECT!
CO_PROCESS_RING = "ProcessRing"
CO_VARIABLE_RING = "VariableRing"
CO_NAME = "Name"
CO_COEF = "Coefficient"
CO_DIRECTION = "Direction"


CO_LINETYPE = "LineType"
CO_LINECOLOR = "LineColor"
CO_LINEWIDTH = "LineWidth"

# process properties
PR_CONNECTIONLIST = "ConnectionList"

# variable properties
VR_CONNECTIONLIST = "ConnectionList"


# system properties
SY_INSIDE_DIMENSION_X = "InsideDimensionX"
SY_INSIDE_DIMENSION_Y = "InsideDimensionY"
SY_PASTE_CONNECTIONLIST = "PasteConnectionList"

# selector variable
PE_SELECTOR = "Selector"
PE_VARIABLE ="Variable"
PE_PROCESS = "Process"
PE_SYSTEM= "System"
PE_CUSTOM = "Custom"
PE_TEXT =  "Text"


# local/global properties

GLOBALPROPERTYSET = [ CO_COEF, CO_NAME, OB_SHAPE_TYPE, CO_LINETYPE ]
MODELPROPERTYSET = [ CO_COEF, CO_NAME ]

### CANVAS CONSTANTS

# shape types
SHAPE_TYPE_SQUARE = "Square"
SHAPE_TYPE_VARIABLE = "Variable"
SHAPE_TYPE_PROCESS = "Process"
SHAPE_TYPE_SYSTEM = "System"
SHAPE_TYPE_TEXTBOX = "TextBox"
SHAPE_TYPE_CUSTOM = "Custom"

# layout properties
LO_SCROLL_REGION = "ScrollRegion" # list of int
LO_ZOOM_RATIO ="Zoom ratio"

#SHAPEDESCRIPTOR properties
SD_NAME = 0
SD_TYPE = 1
SD_FUNCTION = 2
SD_COLOR = 3
SD_Z = 4
SD_SPECIFIC = 5
SD_PROPERTIES = 6


#specific descriptors
RECT_RELX1 = 0
RECT_RELY1 = 1
RECT_RELX2 = 2
RECT_RELY2 = 3
RECT_ABSX1 = 4
RECT_ABSY1 = 5
RECT_ABSX2 = 6
RECT_ABSY2 = 7

LINE_POINTS = 0 # [ x1abs, x1rel, y1abs, y1rel,... ]
LINE_WIDTH = 1


TEXT_TEXT = 0
TEXT_RELX = 1
TEXT_RELY = 2
TEXT_ABSX = 3
TEXT_ABSY = 4

# parameters for SD_FUNCTION and SD_COLOR
SD_OUTLINE = 0
SD_FILL = 1
SD_TEXT = 2
SD_RING = 3 # initates connectionobject by mousedrag
SD_NONE = 4 # does nothing by mousedrag
SD_SYSTEM_CANVAS = 5


#gnome canvasobjects:
CV_RECT = "CanvasRect"
CV_ELL = "CanvasEllipse"
CV_TEXT = "CanvasText"
CV_LINE = "CanvasLine"

