#!/usr/bin/env ecell3-python

import os
import sys
import string

ECELL3_LIBDIR = os.environ['ECELL3_LIBDIR']
MEPATH = ECELL3_LIBDIR + os.sep + 'modeleditor'
PYTHONPATH = os.environ['PYTHONPATH']
os.environ['PYTHONPATH'] = MEPATH + os.pathsep + PYTHONPATH 
os.environ['MEPATH'] = MEPATH

# remove this!!
os.environ['OSOGOPATH'] = ECELL3_LIBDIR + os.sep + 'osogo'

if os.name == 'nt':
    os.popen('python' + ' ' + '\"' + MEPATH + '\"' + os.sep + 'opengui.py' + ' \"' + string.join( sys.argv[1:], '\" \"' ) + '\"')
else:
    os.system('python' + ' ' + '\"' + MEPATH + '\"' + os.sep + 'opengui.py' + ' \"' + string.join( sys.argv[1:], '\" \"' ) + '\"')

