#!/usr/bin/env ecell3-python

import os
import sys
import string

MEPATH = os.environ['MEPATH']
PYTHONPATH = os.environ['PYTHONPATH']
os.environ['PYTHONPATH'] = MEPATH + os.pathsep + PYTHONPATH 

os.popen('python' + ' ' + '\"' + MEPATH + '\"' + os.sep + 'opengui.py' + ' \"' + string.join( sys.argv[1:], '\" \"' ) + '\"')

