#!/usr/bin/env ecell3-python

import os
import sys
import string

import ecell.ecs
import ecell.config

ecell.ecs.setDMSearchPath( os.pathsep.join( ecell.config.dm_path ) )

import ecell.ui.osogo.opengui as opengui
try:
    opengui.main()
except KeyboardInterrupt:
    sys.exit(1)

