#!/usr/bin/env ecell3-python

import os
import sys
import string

import ecell.ecs
import ecell.config

ecell.ecs.setDMSearchPath( os.pathsep.join( ecell.config.dm_path ) )

os.environ[ 'SESSIONMONITORPATH' ] = os.path.join( ecell.config.lib_dir, 'session-monitor' )

sys.path.insert( 0, os.environ[ 'SESSIONMONITORPATH' ] )

import opengui
try:
    opengui.main()
except KeyboardInterrupt:
    sys.exit(1)

