#!/usr/bin/env ecell3-python

import os
import sys
import string

oldcommand = sys.argv[0]
newcommand = 'ecell3-session-monitor'
commandline = newcommand + ' ' + string.join( sys.argv[1:], '\" \"' )

print 'WARNING: %s was renamed to %s. Invoking %s.' % ( oldcommand, newcommand, newcommand )

if os.name == 'nt':
    os.popen( commandline )
else:
    os.system( commandline )
