#!/usr/bin/env ecell3-python

import os
import sys
import string

ECELL3_LIBDIR = os.environ['ECELL3_LIBDIR']
SESSIONMONITORPATH = ECELL3_LIBDIR + os.sep + 'session-monitor'
PYTHONPATH = SESSIONMONITORPATH + os.pathsep + os.environ['PYTHONPATH']

os.environ['SESSIONMONITORPATH'] = SESSIONMONITORPATH
os.environ['PYTHONPATH'] = SESSIONMONITORPATH + os.pathsep + PYTHONPATH
os.environ['LANG'] = 'C'

if os.name == 'nt':
    os.popen('python' + ' ' + '\"' + SESSIONMONITORPATH + '\"' + os.sep + 'opengui.py' + ' \"' + string.join( sys.argv[1:], '\" \"' ) + '\"')
else:
    os.system('python' + ' ' + '\"' + SESSIONMONITORPATH + '\"' + os.sep + 'opengui.py' + ' \"' + string.join( sys.argv[1:], '\" \"' ) + '\"')
