#!/usr/bin/python

import os
import sys

import ecell.ecs
import ecell.config

ecell.ecs.setDMSearchPath( os.pathsep.join( ecell.config.dm_path ) )

os.environ[ 'MEPATH' ] = os.path.join( ecell.config.lib_dir, 'model-editor' )
os.environ[ 'SESSIONMONITORPATH' ] = os.path.join( ecell.config.lib_dir, 'session-monitor' )
os.environ[ 'ECELL3_PREFIX' ] = ecell.config.prefix
os.environ[ 'ECELL3_LIBDIR' ] = ecell.config.lib_dir
os.environ[ 'VERSION' ] = ecell.config.version
sys.path[ 0: 0 ] = [ os.environ[ 'MEPATH' ], os.environ[ 'SESSIONMONITORPATH' ] ]

import ecell.ui.model_editor.opengui as opengui
opengui.main()
