#!/usr/bin/env ecell3-python

import os
import sys
import string

OSOGOPATH = os.environ['OSOGOPATH']
PYTHONPATH = os.environ['PYTHONPATH']
os.environ['PYTHONPATH'] = OSOGOPATH + os.pathsep + PYTHONPATH
os.environ['LANG'] = 'C'

os.popen('python' + ' ' + '\"' + OSOGOPATH + '\"' + os.sep + 'opengui.py' + ' \"' + string.join( sys.argv[1:], '\" \"' ) + '\"')
