#!/usr/bin/env ecell3-python

import os
import sys
import string

ECELL3_LIBDIR = os.environ['ECELL3_LIBDIR']
OSOGOPATH = ECELL3_LIBDIR + os.sep + 'osogo'
PYTHONPATH = OSOGOPATH + os.pathsep + os.environ['PYTHONPATH']

os.environ['OSOGOPATH'] = OSOGOPATH
os.environ['PYTHONPATH'] = OSOGOPATH + os.pathsep + PYTHONPATH
os.environ['LANG'] = 'C'

if os.name == 'nt':
    os.popen('python' + ' ' + '\"' + OSOGOPATH + '\"' + os.sep + 'opengui.py' + ' \"' + string.join( sys.argv[1:], '\" \"' ) + '\"')
else:
    os.system('python' + ' ' + '\"' + OSOGOPATH + '\"' + os.sep + 'opengui.py' + ' \"' + string.join( sys.argv[1:], '\" \"' ) + '\"')
