#!/bin/sh

export PYTHONPATH="."
LD_PRELOAD="/home/ecell/ecell3/ecell/libemc/.libs/libemc.so /home/ecell/ecell3/ecell/libecs/.libs/libecs.so /home/ecell/ecell3/korandom/.libs/libkorandom.so" /usr/bin/python2 $* 
