#!/usr/bin/env python
#::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::
#
#       This file is part of the E-Cell System
#
#       Copyright (C) 1996-2007 Keio University
#       Copyright (C) 2005-2007 The Molecular Sciences Institute
#
#::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::
#
#
# E-Cell System is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public
# License as published by the Free Software Foundation; either
# version 2 of the License, or (at your option) any later version.
# 
# E-Cell System is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
# See the GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public
# License along with E-Cell System -- see the file COPYING.
# If not, write to the Free Software Foundation, Inc.,
# 59 Temple Place - Suite 330, Boston, MA 02111-1307, USA.
# 
#END_HEADER

import os
import pygtk
pygtk.require('2.0')
import gtk
import getopt
import sys

import ecell.ecs
import ecell.ui.model_editor.config as config
from ecell.ui.model_editor.ModelEditor import ModelEditor

def usage():
    print '''
E-Cell System Version 3 Model Editor

(C) 2003-2007 Keio University. All Rights Reserved.

E-Cell System is free software; you can redistribute it and/or modify it
under the terms of the GNU General Public License as published by the
Free Software Foundation; either version 2 of the License, or
(at your option) any later version.

Authors:
  Gabor Bereczki <gabor.bereczki@talk21.com>
  Sylvia Kinta
  Dini Karnag

Usage: %s [-f filename] [-h]

    -f   file to load.
    -h   prints this help.
    ''' % sys.argv[0]

aFileName = None
if len( sys.argv )>1:
    try:
        optstrings = getopt.getopt( sys.argv[1:], 'f:h' )[0]
    except:
        usage()
        sys.exit( 1 )
        
    if len( optstrings ) > 0:
        for anOpt in optstrings:
            if anOpt[0] == '-h':
                print usageString
                sys.exit(0)
            elif anOpt[0] == '-f':
                aFileName = anOpt[1]
        if aFileName == None:
            print usageString
            sys.exit(1)

ecell.ecs.setDMSearchPath( os.pathsep.join( config.dm_path ) )

g = ModelEditor()
if aFileName:
    g.loadModel( aFileName ) 
g.initUI()

gtk.main()


