#!/usr/bin/env ecell3-python

import os
import sys
import string

import ecell.ecs
import ecell.config

ecell.ecs.setDMSearchPath( os.pathsep.join( ecell.config.dm_path ) )

os.environ[ 'MEPATH' ] = os.path.join( ecell.config.lib_dir, 'model-editor' )
os.environ[ 'SESSIONMONITORPATH' ] = os.path.join( ecell.config.lib_dir, 'session-monitor' )
sys.path[ 0: 0 ] = [ os.environ[ 'MEPATH' ], os.environ[ 'SESSIONMONITORPATH' ] ]

import opengui
opengui.main()
