#!/usr/bin/env ecell3-python

import os
import sys
import string

ECELL3_LIBDIR = os.environ['ECELL3_LIBDIR']
MEPATH = ECELL3_LIBDIR + os.sep + 'model-editor'
# remove this!!
SESSIONMONITORPATH = ECELL3_LIBDIR + os.sep + 'session-monitor'


os.environ['SESSIONMONITORPATH'] = SESSIONMONITORPATH
os.environ['PYTHONPATH'] =  MEPATH + os.pathsep + SESSIONMONITORPATH + os.pathsep + os.environ['PYTHONPATH'] 
os.environ['MEPATH'] = MEPATH

os.execve(sys.executable, [
    '-',
    MEPATH + os.sep + 'opengui.py'
    ] + sys.argv[1:], os.environ)
