#!/usr/bin/env ecell3-python

import os
import sys
import string

ECELL3_LIBDIR= os.environ['ECELL3_LIBDIR']
TLPATH=ECELL3_LIBDIR + os.sep + 'toollauncher'
TL_MISC_PATH = TLPATH + os.sep + 'misc'

# remove this!!
SESSIONMONITORPATH = ECELL3_LIBDIR + os.sep + 'session-monitor'

PYTHONPATH = os.environ['PYTHONPATH']
os.environ['PYTHONPATH'] = SESSIONMONITORPATH + os.pathsep + TLPATH + os.pathsep + TL_MISC_PATH + os.pathsep + PYTHONPATH
os.environ['TLPATH'] = TLPATH

os.execve(sys.executable, [
    '-',
    TLPATH + os.sep + 'ToolLauncher.py'
    ] + sys.argv[1:], os.environ)
